version: '3'

services:
  api-server:
    pull_policy: always
    build: 
      context: .
      dockerfile: ./docker/api-server/Dockerfile
    ports:
      - 8080:8080
    command: air -c docker/api-server/.air.toml
    volumes:
      - .:/app